# Structured Data: NumPy's Structured Arrays

While often our data can be well represented by a homogeneous array of values, sometimes this is not the case. This section demonstrates the use of NumPy's *structured arrays* and *record arrays*, which provide efficient storage for compound, heterogeneous data.  While the patterns shown here are useful for simple operations, scenarios like this often lend themselves to the use of Pandas ``Dataframe``s, which we'll explore in [Chapter 3](03.00-Introduction-to-Pandas.ipynb).

In [2]:
import numpy as np

Imagine that we have several categories of data on a number of people (say, name, age, and weight), and we'd like to store these values for use in a Python program.
It would be possible to store these in three separate arrays:

In [3]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

But this is a bit clumsy. There's nothing here that tells us that the three arrays are related; it would be more natural if we could use a single structure to store all of this data.
NumPy can handle this through structured arrays, which are arrays with compound data types.

Recall that previously we created a simple array using an expression like this:

In [4]:
x = np.zeros(4, dtype=int)
x

array([0, 0, 0, 0])

We can similarly create a structured array using a compound data type specification:

In [5]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


Here ``'U10'`` translates to "Unicode string of maximum length 10," ``'i4'`` translates to "4-byte (i.e., 32 bit) integer," and ``'f8'`` translates to "8-byte (i.e., 64 bit) float."
We'll discuss other options for these type codes in the following section.

Now that we've created an empty container array, we can fill the array with our lists of values:

In [6]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


As we had hoped, the data is now arranged together in one convenient block of memory.

The handy thing with structured arrays is that you can now refer to values either by index or by name:

In [7]:
# Get all names
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [8]:
# Get first row of data
data[0]

np.void(('Alice', 25, 55.0), dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [9]:
# Get the name from the last row
data[-1]['name']

np.str_('Doug')

Using Boolean masking, this even allows you to do some more sophisticated operations such as filtering on age:

In [10]:
# Get names where age is under 30
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

Note that if you'd like to do any operations that are any more complicated than these, you should probably consider the Pandas package, covered in the next chapter.
As we'll see, Pandas provides a ``Dataframe`` object, which is a structure built on NumPy arrays that offers a variety of useful data manipulation functionality similar to what we've shown here, as well as much, much more.

## Creating Structured Arrays

Structured array data types can be specified in a number of ways.
Earlier, we saw the dictionary method:

In [ ]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

# 'names': This is a keyword argument in the np.dtype function that specifies the field names for the structured array.

For clarity, numerical types can be specified using Python types or NumPy ``dtype``s instead:

In [11]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})
# (np.str_, 10): This defines a field that can store a Unicode string with up to 10 characters.


dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

A compound type can also be specified as a list of tuples:

In [12]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

If the names of the types do not matter to you, you can specify the types alone in a comma-separated string:

In [13]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

The shortened string format codes may seem confusing, but they are built on simple principles.
The first (optional) character is ``<`` or ``>``, which means "little endian" or "big endian," respectively, and specifies the ordering convention for significant bits.
The next character specifies the type of data: characters, bytes, ints, floating points, and so on (see the table below).
The last character or characters represents the size of the object in bytes.

| Character        | Description           | Example                             |
| ---------        | -----------           | -------                             | 
| ``'b'``          | Byte                  | ``np.dtype('b')``                   |
| ``'i'``          | Signed integer        | ``np.dtype('i4') == np.int32``      |
| ``'u'``          | Unsigned integer      | ``np.dtype('u1') == np.uint8``      |
| ``'f'``          | Floating point        | ``np.dtype('f8') == np.int64``      |
| ``'c'``          | Complex floating point| ``np.dtype('c16') == np.complex128``|
| ``'S'``, ``'a'`` | String                | ``np.dtype('S5')``                  |
| ``'U'``          | Unicode string        | ``np.dtype('U') == np.str_``        |
| ``'V'``          | Raw data (void)       | ``np.dtype('V') == np.void``        |

## More Advanced Compound Types

It is possible to define even more advanced compound types.
For example, you can create a type where each element contains an array or matrix of values.
Here, we'll create a data type with a ``mat`` component consisting of a $3\times 3$ floating-point matrix:

In [17]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.ones(2, dtype=tp)
print(X)
print(X['mat'][0])

[(1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]])
 (1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]])]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Now each element in the ``X`` array consists of an ``id`` and a $3\times 3$ matrix.
Why would you use this rather than a simple multidimensional array, or perhaps a Python dictionary?
The reason is that this NumPy ``dtype`` directly maps onto a C structure definition, so the buffer containing the array content can be accessed directly within an appropriately written C program.
If you find yourself writing a Python interface to a legacy C or Fortran library that manipulates structured data, you'll probably find structured arrays quite useful!

## RecordArrays: Structured Arrays with a Twist

NumPy also provides the ``np.recarray`` class, which is almost identical to the structured arrays just described, but with one additional feature: fields can be accessed as attributes rather than as dictionary keys.
Recall that we previously accessed the ages by writing:

np.recarray is a subclass of NumPy's ndarray that allows field access by attribute rather than by index. It is particularly useful for working with structured data where you want to access fields (columns) using attribute-style access rather than dictionary-style indexing.

If we view our data as a record array instead, we can access this with slightly fewer keystrokes:

In [18]:
import numpy as np

# Define a structured dtype
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f8')]

# Create a recarray
data = np.recarray((3,), dtype=dtype)

# Assign values
data.name = ['Alice', 'Bob', 'Charlie']
data.age = [25, 30, 35]
data.weight = [55.5, 75.0, 68.0]

# Access fields
print(data.name)   # Output: ['Alice' 'Bob' 'Charlie']
print(data.age)    # Output: [25 30 35]
print(data.weight) # Output: [55.5 75.  68. ]
print(data)

['Alice' 'Bob' 'Charlie']
[25 30 35]
[55.5 75.  68. ]
[('Alice', 25, 55.5) ('Bob', 30, 75. ) ('Charlie', 35, 68. )]


### Advantages:
- **Attribute Access**: Easier and more readable access to fields using dot notation.
- **Compatibility**: Works well with structured dtypes in NumPy.

### Limitations:
- **Performance**: Slightly slower than regular `ndarray` for large data due to the overhead of attribute access.
- **Memory Overhead**: Slightly more memory usage compared to `ndarray` because of the additional attribute dictionary.
The downside is that for record arrays, there is some extra overhead involved in accessing the fields, even when using the same syntax. We can see this here:

In [19]:
%timeit data['age']
%timeit data.age



2.77 μs ± 308 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
5.23 μs ± 273 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
