# Preprocessing with NumPy
Preprocessing with NumPy is an essential step in preparing data for analysis, machine learning, or statistical modeling. It involves cleaning, transforming, and organizing data to ensure it's in a format that's ready for further use. NumPy, with its array-based operations, is a powerful tool for performing data preprocessing tasks efficiently.



In [2]:
import numpy as np

## Loading Data
You can load data from various sources using NumPy.

In [5]:
data = np.genfromtxt("Lending-Company-Numeric-Data-NAN-short.csv",
                                            delimiter=';', skip_header=1)
print(data)

[[ 4. nan  6.]
 [ 7.  8. nan]
 [nan 10. 11.]]


## Checking for Missing Values

In [6]:
import numpy as np

# Example data
data = np.array([[1, 2, np.nan],
                                    [4, np.nan, 6],
                                    [7, 8, 9]])

# Counting NaN values
num_nans = np.isnan(data).sum()

print(f"Number of NaN values: {num_nans}")

Number of NaN values: 2


In [7]:
data = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter=';', skip_header=1)
print(np.isnan(data).sum())


260


In [8]:
data = np.genfromtxt("Lending-Company-Numeric-Data-NAN-short.csv",
                                            delimiter = ';',
                                            filling_values = 0)
print(data)

## Filling_values substitutes every nan with the value we're passing (0 in this case)

[[ 1.  2.  3.]
 [ 4.  0.  6.]
 [ 7.  8.  0.]
 [ 0. 10. 11.]]


In [9]:
np.isnan(data).sum()

## All the previously missing values are now 0s.

np.int64(0)

In [11]:
data = np.genfromtxt("Lending-Company-Numeric-Data-NAN-short.csv",
                              
                                            delimiter = ';') 
data
# We need to reimport the dataset since all the missing values are filled up. 

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8., nan],
       [nan, 10., 11.]])

In [12]:
temporary_fill = np.nanmax(data).round(2) + 1
# np.nanmax() calculates the maximum value of the array while ignoring any NaN values.
# This means that if lending_co_data_numeric_NAN contains missing values (NaN), 
# they are not considered when calculating the maximum value. Only the valid numbers are used.

# round(2) This step ensures that the maximum value is rounded to two decimal places,
#  making it easier to handle in further calculations.

# We use nanmax(), since max() returns nan. 
# We want a value greater than the max, since we have be certain it's unique to the dataset.

In [13]:
temporary_fill

np.float64(12.0)

In [14]:
data_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN-short.csv",
                                            delimiter = ';',
                                            filling_values = temporary_fill) 
data_NAN
# Filling up all the missing values with the temporary filler. 

array([[ 1.,  2.,  3.],
       [ 4., 12.,  6.],
       [ 7.,  8., 12.],
       [12., 10., 11.]])

In [15]:
np.isnan(data_NAN)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
np.isnan(data_NAN).sum()

np.int64(0)

In [25]:
data_NAN

array([[ 1.,  2.,  3.],
       [ 4., 12.,  6.],
       [ 7.,  8., 12.],
       [12., 10., 11.]])

## Substituting Missing Values

np.where() is a conditional function in NumPy that returns elements chosen from two options:

If the condition is True, it selects the value x.

If the condition is False, it selects the value y.

In [37]:
data = np.array([1, 2, np.nan, 4, 5])
print(data)  # Output: [ 1.  2. nan  4.  5.]
data_filled = np.where(np.isnan(data), 0, data)
print(data_filled)  # Output: [1. 2. 0. 4. 5.]


[ 1.  2. nan  4.  5.]
[1. 2. 0. 4. 5.]


In [38]:
mean_value = np.nanmean(data)  # Calculate mean excluding NaN
data_filled = np.where(np.isnan(data), mean_value, data)
print(data_filled)  # Output: [1. 2. 3. 4. 5.]


[1. 2. 3. 4. 5.]


In [39]:
median_value = np.nanmedian(data)  # Calculate median excluding NaN
data_filled = np.where(np.isnan(data), median_value, data)
print(data_filled)  # Output: [1. 2. 3. 4. 5.]



[1. 2. 3. 4. 5.]


## Reshaping
In reshaping, NumPy simply flattens the original array and fills the new shape (6 rows and 1043 columns) in row-major order.

Reshaping an array means changing the shape of the array without modifying its data, but it involves reordering the elements of the array to fit the new shape.
In reshaping, the elements are rearranged in the order they appear, which can result in a different layout of data in memory.
Reshaping can change the number of rows and columns (or more generally, the shape of the array) but doesn't guarantee the same structure of data as before.


In [21]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)

print("Original array:", arr)
print("Reshaped array:\n", reshaped_arr)


Original array: [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [22]:
import numpy as np

# Create a 2D array (3x4 matrix)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Original 2D array:")
print(arr)

# Reshape the array into a 4x3 matrix
reshaped_arr = arr.reshape(4, 3)

print("\nReshaped array (4x3):")
print(reshaped_arr)


Original 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped array (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", delimiter = ',')

In [18]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [19]:
lending_co_data_numeric.shape

(1043, 6)

In [20]:
np.reshape(lending_co_data_numeric, (6,1043))

# Reshaping (1043,6) to (6,1043) is not the same as transposing.

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]],
      shape=(6, 1043))

In [44]:
np.transpose(lending_co_data_numeric)

array([[ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [13621., 15041., 15340., ..., 16600., 15600., 16600.]],
      shape=(6, 1043))

# **Reshaping vs Transposing in NumPy**

Reshaping and transposing a NumPy array are not the same operations. While both modify the structure of the array, they do so in different ways.

---

## **Key Differences**

1. **Reshaping**:
   - Changes the shape of the array by rearranging its elements in row-major order.
   - Does not preserve the relative positions of elements as they were in the original array.

2. **Transposing**:
   - Flips the rows and columns of the array (or swaps axes for higher dimensions).
   - Preserves the relative positions of elements.

---

## **Example**



In [46]:
import numpy as np
arr = np.array([[1, 2, 3,4,5,500],
                [4, 5, 6,7,8,800]])
print(arr.shape)
reshaped = arr.reshape(3, 4)
print("reshaped")

print(reshaped)
print("transposed")

transposed = arr.T
print(transposed)

(2, 6)
reshaped
[[  1   2   3   4]
 [  5 500   4   5]
 [  6   7   8 800]]
transposed
[[  1   4]
 [  2   5]
 [  3   6]
 [  4   7]
 [  5   8]
 [500 800]]


## Removing Values

In [47]:
import numpy as np

# Create a 1D array
data = np.array([1, 2, 3, 4, 5])

# Delete the element at index 2
result = np.delete(data, 2)
print(result)  # Output: [1 2 4 5]


[1 2 4 5]


In [48]:
# Create a 2D array
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Delete the second row (index 1)
result = np.delete(data_2d, 1, axis=0) # axis = 0 for row
print(result)
# Output:
# [[1 2 3]
#  [7 8 9]]


[[1 2 3]
 [7 8 9]]


In [ ]:
# Delete the third column (index 2)
result = np.delete(data_2d, 2, axis=1)
print(result)
# Output:
# [[1 2]
#  [4 5]
#  [7 8]]


In [ ]:
# Delete elements from index 1 to 4 (exclusive)
result = np.delete(data, slice(1, 4))
print(result)  # Output: [1 5]


In [ ]:
# Delete the element at index 4 in the flattened array
result = np.delete(data_2d, 4)
print(result)  # Output: [1 2 3 4 6 7 8 9]


In [65]:
lending_co_data_numeric1=np.delete(lending_co_data_numeric, 0)
print(lending_co_data_numeric1)
print(lending_co_data_numeric1.shape)



# If you do not specify the axis parameter,
#  np.delete() will flatten the array before performing the deletion.
#  This means that the entire array is considered as a 1D array, 
# and the deletion will remove an element from this 1D version of the array.



# As a result, the array is flattened, and the first element (index 0) is removed, 
# which will affect the total number of elements in the array.
#  The total number of elements decreases by one.



# Removes the first value of the flattened array. 

[   40.   365.  3121. ...  4601.  4601. 16600.]
(6257,)


In [70]:
arr = np.array([[1, 2, 3, 4, 5, 500],
                [4, 5, 6, 7, 8, 800],
                [400, 59, 26, 7, 8, 800],
                [34, 533, 6, 7, 8, 800]])
arr1=np.delete(arr, [0, 2], axis=0)

print(arr1)

# By setting an axis, we can simultaneously delete entire rows or columns. 
# [0, 2, 4]:
# A list of column indices to delete. Here, columns at indices 0, 2, and 4 are targeted.

[[  4   5   6   7   8 800]
 [ 34 533   6   7   8 800]]


In [24]:
import numpy as np

# Sample 5x5 matrix (lending_co_data_numeric)
lending_co_data_numeric = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

print("Original Array:")
print(lending_co_data_numeric)

# Perform the nested np.delete operation
result = np.delete(np.delete(lending_co_data_numeric, [0, 2, 4], axis=1), [0, 2, -1], axis=0)

print("\nArray after deleting columns [0, 2, 4] and rows [0, 2, -1]:")
print(result)

# We can simultaneously delete rows AND columns. 

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array after deleting columns [0, 2, 4] and rows [0, 2, -1]:
[[ 7  9]
 [17 19]]


## Sorting Data

In [49]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

### Sorting along rows or columns
A useful feature of NumPy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the ``axis`` argument. For example:

In [3]:
# np.random.RandomState() constructs a random number generator. It does not have any effect
rand = np.random.RandomState(42)
# on the freestanding functions in np.random, but must be used explicitly:

X = rand.randint(0, 10, (4, 6))  # gives the start,end,vector dimension
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [4]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [5]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [6]:
np.sort(X, axis=None) #axis works differently
# Flatten the array and sort

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 7, 7,
       9, 9])

## Partial Sorts: Partitioning

Sometimes we're not interested in sorting the entire array, but simply want to find the *k* smallest values in the array. NumPy provides this in the ``np.partition`` function. ``np.partition`` takes an array and a number *K*; the result is a new array with the smallest *K* values to the left of the partition, and the remaining values to the right, in arbitrary order:

np.partition(x, k) ensures that the element at the k-th index is in its correct position as it would be in the sorted array.

In [53]:
x = np.array([7, 200, 300, 11, 16, 51, 4])

# Partition the array with index 5 
result = np.partition(x, 5)
print(result)


[  4   7  11  16  51 200 300]


In [55]:
import numpy as np

X = np.array([[7, 2, 3, 1, 6, 5, 4],
              [9, 8, 7, 6, 5, 4, 3]])

# Partition the 2D array along rows (axis=1) at index 2
result = np.partition(X, 2, axis=1)
print(result)


[[1 2 3 4 5 6 7]
 [3 4 5 6 7 8 9]]


In [56]:
import numpy as np

X = np.array([[7, 2, 3, 1, 6, 5, 4],
              [9, 8, 7, 6, 5, 4, 3],
              [5, 6, 2, 9, 8, 7, 1]])

# Partition the 2D array along columns (axis=0) at index 2
result = np.partition(X, 2, axis=0)
print(result)
# sorting for second column element

[[5 2 2 1 5 4 1]
 [7 6 3 6 6 5 3]
 [9 8 7 9 8 7 4]]


## Argument Functions

### np.argsort()
# **`np.argsort()`**:

The **`np.argsort()`** function in NumPy is used to get the indices that would sort an array. Instead of returning the sorted values, it provides the positions of the elements in the sorted order.

---

## **Syntax**
```python
numpy.argsort(a, axis=-1, kind=None, order=None)


In [27]:
import numpy as np

# Sample 1D array
arr = np.array([40, 10, 100, 90, 20])

# Get the indices that would sort the array
indices = np.argsort(arr)

print("Original array:", arr)
print("Sorted indices:", indices)


Original array: [ 40  10 100  90  20]
Sorted indices: [1 4 0 3 2]


In [28]:
# Sort the array using the indices
sorted_arr = arr[indices]

print("Sorted array:", sorted_arr)


Sorted array: [ 10  20  40  90 100]


In [29]:
# Sort in descending order
sorted_indices_desc = np.argsort(arr)[::-1]

print("Sorted indices (descending):", sorted_indices_desc)

# Sort the array in descending order using the indices
sorted_arr_desc = arr[sorted_indices_desc]

print("Sorted array (descending):", sorted_arr_desc)


Sorted indices (descending): [2 3 0 4 1]
Sorted array (descending): [100  90  40  20  10]


In [31]:
# Sample 2D array
arr_2d = np.array([[3, 2, 1], [6, 5, 4]])

# Get the indices that would sort the array along axis 0 (column-wise)
indices_0 = np.argsort(arr_2d, axis=0)

print("Sorted indices along axis 0 (column-wise):")
print(indices_0)

# Get the indices that would sort the array along axis 1 (row-wise)
indices_1 = np.argsort(arr_2d, axis=1)

print("\nSorted indices along axis 1 (row-wise):")
print(indices_1)


Sorted indices along axis 0 (row-wise):
[[0 0 0]
 [1 1 1]]

Sorted indices along axis 1 (column-wise):
[[2 1 0]
 [2 1 0]]


In [32]:
np.argsort(arr_2d)

# np.argsort() is a function in NumPy that returns the indices that would sort an array.
#  In other words, it does not sort the array itself, but instead, 
# it provides the indices that can be used to sort the array.

# The resulting array from np.argsort() is a 1D array of indices,
#  and these indices represent the order in which the original elements would 
# need to be arranged in ascending order.

# Returns the order which will sort the array. 

array([[2, 1, 0],
       [2, 1, 0]])

In [37]:
import numpy as np

# Sample 2D array
arr_2d = np.array([[3, 2, 1], 
                   [6, 5, 4]])

# Get the indices that would sort the flattened 2D array
indices_2d = np.argsort(arr_2d)

print("Original 2D array:")
print(arr_2d)

# Output the indices that would sort the flattened array
print("\nSorted indices (flattened):", indices_2d)

# Use the indices to sort the flattened array
# sorted_arr_2d = arr_2d[indices_2d]
# print("\nSorted array (flattened):", sorted_arr_2d)


Original 2D array:
[[3 2 1]
 [6 5 4]]

Sorted indices (flattened): [[2 1 0]
 [2 1 0]]


### np.argwhere()
# **`np.argwhere()`**: Explanation

The **`np.argwhere()`** function in NumPy is used to find the indices of elements in an array that satisfy a given condition. It returns the indices of the matching elements in a structured format.

---



In [57]:
lending_co_data_numeric = np.array([[1, 2, 3, 4, 5, 500],
                                          [4, 5, 6, 7, 8, 800],
                                          [400, np.nan, 0, 7, 8, 800],
                                          [34, 533, 6, 7, 8, 800]])

lending_co_data_numeric

array([[  1.,   2.,   3.,   4.,   5., 500.],
       [  4.,   5.,   6.,   7.,   8., 800.],
       [400.,  nan,   0.,   7.,   8., 800.],
       [ 34., 533.,   6.,   7.,   8., 800.]])

In [58]:
np.argwhere(lending_co_data_numeric == False)

# Default condition is to return values are false 0. 

array([[2, 2]])

In [63]:
lending_co_data_numeric

array([[  1.,   2.,   3.,   4.,   5., 500.],
       [  4.,   5.,   6.,   7.,   8., 800.],
       [400.,  nan,   0.,   7.,   8., 800.],
       [ 34., 533.,   6.,   7.,   8., 800.]])

In [62]:
np.argwhere(lending_co_data_numeric %2 == 0)
# Return the indices where even values
# The condition can be more complex 

array([[0, 1],
       [0, 3],
       [0, 5],
       [1, 0],
       [1, 2],
       [1, 4],
       [1, 5],
       [2, 0],
       [2, 2],
       [2, 4],
       [2, 5],
       [3, 0],
       [3, 2],
       [3, 4],
       [3, 5]])

In [64]:
np.isnan(lending_co_data_numeric).sum()

np.int64(1)

In [65]:
lending_co_data_numeric = np.array([[1, 2, 3, 4, 5, 500],
                                    [4, 5, 6, 7, 8, 800],
                                    [400, np.nan, 0, 7, 8, 800],
                                    [34, 533, 6, 7, 8, 800]])
np.argwhere(np.isnan(lending_co_data_numeric))



# Returns the coordinates of all the missing values within the array. 

array([[2, 1]])

## Shuffling Data

Shuffling data is a common step in data preprocessing to ensure that the order of the data does not influence the outcome of your model or analysis. NumPy provides tools for shuffling arrays easily.

---

## **Shuffling with `np.random.shuffle()`**

### **Syntax**
```python
np.random.shuffle(arr)


In [7]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Shuffle the array
np.random.shuffle(arr)

print(arr)

[1 3 4 2 5]


In [8]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Shuffle the array
np.random.shuffle(arr)

print(arr) #Output (rows shuffled, columns intact):

# No direct function to shuffle column


[[4 5 6]
 [7 8 9]
 [1 2 3]]


You can transpose the array, shuffle the rows of the transposed array (which correspond to the columns of the original array), and then transpose it back.


In [66]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr.T)
# Shuffle the columns
np.random.shuffle(arr.T)

print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


## Casting

In [111]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", delimiter = ',') 
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [112]:
lending_co_data_numeric.astype(dtype = np.int32)

# Creates an integer version of the array. 

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]], dtype=int32)

In [113]:
lending_co_data_numeric = lending_co_data_numeric.astype(dtype = str)

# We need to overwrite the variable in order to work with strings. 

In [114]:
lending_co_data_numeric

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [ ]:
type(lending_co_data_numeric)

In [115]:
lending_co_data_numeric = lending_co_data_numeric.astype(dtype = np.float32)
lending_co_data_numeric.astype(dtype = np.int32)

## We can't directly cast strings to integers. We can go through floats (string -> float -> integer).

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]], dtype=int32)

In [117]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", delimiter = ',')
lending_co_data_numeric = lending_co_data_numeric.astype(dtype = str)
lending_co_data_numeric

# To showcase the other way to go from strings to integers,
#  we need to get the strings version of the array once again. 

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [ ]:
lending_co_data_numeric.astype(dtype = np.float32).astype(dtype = np.int32)
lending_co_data_numeric

## We can chain methods in NumPy.

## Stripping Data

In [70]:
import numpy as np

# Example array of strings
arr = np.array(['id_12345', 'id_67890', 'id_54321'])

# Use np.char.strip() to remove 'id_' from both the start and end of each string
stripped_array = np.char.strip(arr, 'id_')

print("Stripped array:")
print(stripped_array)


Stripped array:
['12345' '67890' '54321']


## Unique 

In [38]:
import numpy as np

# Sample array


# Find unique elements
unique_elements = np.unique(arr)

print("Unique elements:", unique_elements)


Unique elements: [1 2 3 4 5]


In [39]:
# Find unique elements and their indices in the original array
unique_elements, indices = np.unique(arr, return_index=True)

print("Unique elements:", unique_elements)
print("Indices of unique elements:", indices)


# Unique -> returns the unique values within the array in increasing order

# return_counts -> returns how many times each unique value appears in the array

# return_index -> returns the index of the first encounter with each unique value

Unique elements: [1 2 3 4 5]
Indices of unique elements: [0 1 3 4 7]


In [41]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])

# Find unique elements and their counts
unique_elements, counts = np.unique(arr, return_counts=True)

print("Unique elements:", unique_elements)
print("Counts of unique elements:", counts)


Unique elements: [1 2 3 4 5]
Counts of unique elements: [1 2 1 3 1]


In [42]:
arr_2d = np.array([[1, 2, 3],
                   [1, 2, 3],
                   [4, 5, 6]])

# Find unique rows along axis 0
unique_rows = np.unique(arr_2d, axis=0)

print("Unique rows along axis 0:")
print(unique_rows)


Unique rows along axis 0:
[[1 2 3]
 [4 5 6]]


In [43]:
# Find unique columns along axis 1
unique_columns = np.unique(arr_2d, axis=1)

print("Unique columns along axis 1:")
print(unique_columns)


Unique columns along axis 1:
[[1 2 3]
 [1 2 3]
 [4 5 6]]
