# Working with Arrays

In [1]:
import numpy as np

## Slicing

In [2]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing

In [57]:
matrix_A[:]

## The default start and stop for slicing are the origin and the end of the array. 
## Hence, [:] includes the entire array. 

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(matrix_A[:,:])

## [:,:] -> All rows, and all columns.

numpy.ndarray

In [12]:
matrix_A[:2]

# [:2] -> All the rows up to the 3rd one (excluding the third one).

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
matrix_A[1]

array([4, 5, 6])

In [17]:
matrix_A[:-1]

# [:-1] -> All the rows up to the last one.

array([[1, 2, 3]])

In [18]:
matrix_A[:,1:]

# All the rows, but only the columns from the one with index 1 (second column) onwards.

array([[2, 3],
       [5, 6]])

In [19]:
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
matrix_A[1:,1:]

# All the rows after the first one and all the column after the first one. 

array([[5, 6]])

### Stepwise Slicing

In [21]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [28]:
matrix_B[-1::-1,::2]

# The syntax for each dimension is "[start : stop : step]". 
# A negative step means we're going through the array in reverse.

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

### Conditional Slicing

In [29]:
matrix_C = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [30]:
matrix_C[:,0]

array([1, 3, 4])

In [31]:
matrix_C[:,0] > 2

# Returns True/False based on whether the individual element satisfies the condition. 

array([False,  True,  True])

In [32]:
matrix_C[:,:] > 2

# Returns True/False based on whether the individual element satisfies the condition. 

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [39]:
matrix_C[matrix_C[:,:] % 2 == 0]

# Returns the actual values which satisfy the condition, not simply True or False.

array([2, 0, 6, 6, 4, 4, 8, 0])

In [41]:
matrix_C[(matrix_C[:,:] % 2 == 0) | (matrix_C[:,:] <= 4)]

# We can have more complex conditions, which are comprised of several smaller conditions. 
# & -> Both conditions must be met. 
# | -> Either condition can be met. 

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])

## Dimensions and the Squeeze Function

In [42]:
matrix_D = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [ ]:
type(matrix_D[0,0])

# Fixing both indices. 
# 0-D array
# matrix_D[0, 0] accesses the first element in the first row of the matrix, which is 1.
# This is a scalar value, so matrix_D[0, 0] is a scalar, not an array. Scalars in NumPy do not have a shape.
# shape of a scalar is an empty tuple ().

numpy.int32

In [44]:
print(matrix_D[0,0])

1


In [ ]:
type(matrix_D[0,0:1])

# 1 index is fixed, the second one is a slice
# 1-D array
# matrix_D[0, 0:1] accesses the first row (matrix_D[0]) and slices it from index 0 to index 1. This means we are selecting only the first element of the first row as a 1D array with one element.
# This results in a 1D array with one element: [1].
# The shape of a 1D array with one element is (1,), meaning it has 1 element along the horizontal axis.

numpy.ndarray

In [46]:
print(matrix_D[0,0:1])

[1]


In [ ]:
type(matrix_D[0:1,0:1])

# Both indices are ranges (slices)
# 2-D array
# matrix_D[0:1, 0:1] accesses a slice of the matrix, taking the first row (0:1) and the first column (0:1).
# This means we are selecting a 1x1 submatrix, which is essentially a 2D array containing only the first element of the matrix (i.e., the value 1).
# The shape of this submatrix is (1, 1), which means it has 1 row and 1 column.

numpy.ndarray

In [48]:
print(matrix_D[0:1,0:1])

[[1]]


In [50]:
print(matrix_D[0,0].shape)
print(matrix_D[0,0:1].shape)
print(matrix_D[0:1,0:1].shape)

# Same value stored in 3 different ways -> 0-D, 1-D and 2-D array

()
(1,)
(1, 1)


In [54]:
print(matrix_D[0:1,0:1].squeeze())

## Removes excess dimensions

1


In [55]:
np.squeeze(matrix_D[0:1,0:1])

## The function is equivalent to the method. 

array(1)

In [56]:
print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)

## All excess dimensions are lost and our outputs are aligned. 

()
()
()


In [ ]:
squeeze() is a method in NumPy that removes single-dimensional entries from the shape of an array.
It removes axes (dimensions) where the size is 1. For example:
A 2D array with shape (1, 5) would be squeezed to a 1D array with shape (5,).
A 3D array with shape (1, 1, 3) would be squeezed to a 2D array with shape (3,).