# Statistsics w/ NumPy

In [2]:
import numpy as np

### np.mean()
# **`np.mean`**: Calculating the Mean in NumPy

The `np.mean()` function in the NumPy library is used to calculate the **mean (average)** of elements in an array.

---


In [3]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [4]:
np.mean(matrix_A, axis = 1)

# We can call the function over a given axis (e.g for every row or column when it comes to 2-D arrays)

array([1. , 5.2, 4. ])

In [5]:
matrix_A.mean()

# An equivalent method exists.

np.float64(3.4)

In [ ]:
# matrix_A.sqrt() 

# Results in an attribute error, since not every function has an equivalent method. 

In [6]:
np.mean(matrix_A, axis = 1, dtype = np.int64)

## We can cast the values to a specific type as well. 

array([1, 5, 4])

### Min & Max Values

In [7]:
import numpy as np

In [8]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [9]:
np.min(matrix_A)

# Returns the minimum value. 

np.int64(0)

In [10]:
np.amin(matrix_A)

# Equivalent function (literally just a different alias for np.min())

np.int64(0)

In [11]:
np.minimum(matrix_A[1], matrix_A[2]) # min between 2nd and 3rd rows

# Elementwise minimum. Returns the lowest value out of a given set.
# In this case, np.minimum() returns the lower value every position across the two arrays. (e.g. lowest value in 1st position, 2nd, etc)

array([3, 5, 3, 2, 0])

In [12]:
np.minimum.reduce(matrix_A) # min for column

## A way to make minimum() equivalent to min()

array([1, 0, 0, 2, 0])

In [13]:
np.min(matrix_A, axis = 0)

array([1, 0, 0, 2, 0])

In [14]:
np.max(matrix_A)

## Corresponding max, a max and maximum functions exist. 

np.int64(9)

In [15]:
np.amax(matrix_A)

np.int64(9)

In [16]:
np.maximum.reduce(matrix_A) # min for colum

array([4, 6, 6, 8, 9])

### Statistical Order Functions 

In [17]:
import numpy as np

In [18]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [19]:
np.ptp(matrix_A)

## Returns difference between max and min (peak-to-peak) over the flattened array. 

np.int64(9)

In [20]:
np.ptp(matrix_A, axis = 0)

## Returns difference between max and min (peak-to-peak) for every column. 

array([3, 6, 6, 6, 9])

In [21]:
np.ptp(matrix_A, axis = 1)

## Returns difference between max and min (peak-to-peak) for every row. 

array([3, 7, 8])

In [22]:
np.sort(matrix_A, axis = None)

# A sorted version of the flattened matrix_A

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [23]:
type(np.percentile(matrix_A, 70))
# N-th Percentile = A value which is greater than n% of the dataset. 

numpy.float64

In [24]:
np.percentile(matrix_A, 100)

# 100-th percentile = max
# 50-th percentile = median
# 0-th percentile = min

np.float64(9.0)

In [25]:
np.quantile(matrix_A, 0.70, interpolation = "nearest")

# Quantile -> Similar to percentile, but works with parts of the dataset, rather than percentages. 
# Hence, the N-th Quantile = 100*N-th Percentile of the same dataset. 

np.int64(5)

### Averages and Variances

In [26]:
import numpy as np

In [27]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [28]:
np.median(matrix_A)

# Returns the median for the flattened array. 
# Median -> The middle value of a sorted version of the dataset. 

np.float64(3.0)

In [29]:
np.sort(matrix_A, axis = None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [30]:
np.mean(matrix_A)

# The arithmetic average of the flattened array. 

np.float64(3.4)

In [31]:
np.average(matrix_A)

# The average of the flattened array. 

np.float64(3.4)

In [33]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_RG = gen(pcg(365))

array_weights = array_RG.random(size = (3,5))
print(array_weights)
print(matrix_A)

# Generating some random weights for each entry of matrix_A (for the sake of the example)

[[0.75915734 0.7662218  0.6291028  0.20336599 0.66501486]
 [0.06559111 0.71326309 0.10812106 0.87969046 0.49405844]
 [0.82472673 0.45652944 0.07367232 0.69628564 0.36690736]]
[[1 0 0 3 1]
 [3 6 6 2 9]
 [4 5 3 8 0]]


In [34]:
np.average(matrix_A, weights = array_weights)
# weights: An array of weights that assigns importance to each value in a.
#  This parameter should have the same shape as a. 
# If weights=None (the default), all elements are equally weighted.

# The weighted average of the flattened array. 

np.float64(3.2120290871899306)

In [35]:
np.var(matrix_A)
# np.var() is a function in NumPy used to calculate the variance of an array or along a specified axis.
#  Variance is a statistical measure that describes the spread or 
# dispersion of a set of values in a dataset. 
# It tells you how much the values deviate from the mean (average) of the data.


# The variance of the array. 

np.float64(7.84)

In [ ]:
np.std(matrix_A)
# The np.std() function in NumPy calculates the standard deviation of an array or along a specified axis.
#  Standard deviation is a measure of the amount of variation or dispersion of a set of values. 
# A low standard deviation indicates that the values tend to be close to the mean, whereas a high standard deviation indicates that the values are spread out over a larger range.


# The standard deviation of the array. 

np.float64(2.8)

In [ ]:
2.8**2

### Correlation

In [ ]:
import numpy as np

In [37]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [ ]:
np.cov(matrix_A)
# Covariance is a statistical measure that helps us understand the relationship between two sets of data (variables).
#  Specifically, it tells us whether the two variables tend to increase or decrease together, or
#  if they move independently.

# Simple Explanation of Covariance:
# Imagine you are comparing the heights and weights of a group of people. You want to know:

# If taller people tend to weigh more (positive relationship),
# If taller people tend to weigh less (negative relationship),
# If height and weight don't seem to affect each other much (no relationship).
# The covariance of every row (array) of matrix_A and every other row of the variable. 

array([[ 1.5, -2. ,  2. ],
       [-2. ,  7.7, -7. ],
       [ 2. , -7. ,  8.5]])

In [39]:
np.corrcoef(matrix_A)
# Correlation is a measure that tells us how two sets of data (variables) are related to each other. In simple terms, it answers the question:

# Do two variables change together?
# Do they move in the same direction (both increase or both decrease)?
# Do they move in opposite directions (one increases while the other decreases)?
# Correlation Coefficient:
# The correlation coefficient is a number that quantifies this relationship. It ranges from -1 to 1:

# +1: Perfect positive correlation — as one variable increases, the other increases in a perfectly predictable way.
# -1: Perfect negative correlation — as one variable increases, the other decreases in a perfectly predictable way.
# 0: No correlation — changes in one variable don’t have any predictable effect on the other
# The correlation coefficient of every row (array) of matrix_A and every other row of the variable. 

array([[ 1.        , -0.58848989,  0.56011203],
       [-0.58848989,  1.        , -0.8652532 ],
       [ 0.56011203, -0.8652532 ,  1.        ]])

### Histograms

In [ ]:
import numpy as np

In [ ]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

In [ ]:
np.sort(matrix_A, axis = None)

In [ ]:
np.histogram(matrix_A, bins = 4, range = (1,7))

# Computes the bin edges and how many points fall in each bin. 
# The 1-st array contains the number of points. The 2-nd array contains the bin edges. 

In [ ]:
import matplotlib.pyplot as plt
plt.hist(matrix_A.flat, bins = np.histogram(matrix_A)[1])
plt.show()

# NumPy has no plotting capabilities, so we're using matplotlib's help. 
# .flat -> The flattened version of the array

In [ ]:
matrix_A

In [ ]:
np.histogram2d(matrix_A[0], matrix_A[1], bins = 4)

# We pass two datasets for the 2-D histogram. 

In [ ]:
np.histogramdd(matrix_A.transpose(), bins = 4)

### NaN-Equivalents

In [ ]:
import numpy as np

In [48]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,np.nan]])
matrix_A

array([[ 1.,  0.,  0.,  3.,  1.],
       [ 3.,  6.,  6.,  2.,  9.],
       [ 4.,  5.,  3.,  8., nan]])

In [49]:
np.nanmean(matrix_A)
# The np.nanmean() function in NumPy is used to calculate the mean (average) of an array,
#  but it ignores NaN values. This is useful when you have missing or invalid data (represented as NaN), 
# and you don't want those values to affect the mean calculation.

np.float64(3.642857142857143)

In [45]:
np.mean(matrix_A)

# NAN functions work the same way as non-NAN functions for non-NAN datasets

np.float64(nan)

In [50]:
matrix_B = np.array([[1,0,0,3,1],[3,6,np.nan,2,9],[4,5,3,8,0]])
matrix_B

array([[ 1.,  0.,  0.,  3.,  1.],
       [ 3.,  6., nan,  2.,  9.],
       [ 4.,  5.,  3.,  8.,  0.]])

In [51]:
np.nanmean(matrix_B)

# NAN functions ignore "nan" values and compute the mean. 

np.float64(3.2142857142857144)

In [52]:
np.mean(matrix_B)

# Non-NAN functions return "nan" when missing values are present.

np.float64(nan)

In [53]:
np.nanquantile(matrix_B, 0.7)
# A quantile is a value that divides the data into intervals with a specific proportion of values falling below and above that value.

# In simpler terms, a quantile tells you about the distribution of the data. For example, the 0.5 quantile is the median (the middle value), and the 0.25 and 0.75 quantiles are the first and third quartiles, respectively.

np.float64(4.1)

In [54]:
np.nanvar(matrix_B)
# Variance tells us how much the data values vary or deviate from the mean (average) of the dataset. A high variance indicates that the data points are spread out widely around the mean, while a low variance indicates that the data points are close to the mean.



np.float64(7.882653061224489)